/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////유저 API//////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////
// 회원가입
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name":"lee do yeon",
    "username":"ldy",
    "email":"ldy@gamil.com",
    "password":"password1",
    "address":"korea",
    "phone_number":"010-3333-3333"
}


###
// 로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username":"ldy",
    "password":"password1"
}

/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////상품 API//////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////

###
// 상품등록하기
POST http://localhost:3000/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{
    "category_name" : "커피",
    "subcategory_name": "싱글오리진",
    "size_price":
        [{
            "size":"100g",
            "price":25000
        },{
            "size":"250g",
            "price":50000
        }],
    "taste_name":["Apple", "Mango"],
    "grinding_name":["드립"],
    "product_name" : "두번째 커피",
    "roastingDate" : "2023-01-01"
}



###
// 전체상품리스트
GET http://localhost:3000/products



###
// 특정상품정보
GET http://localhost:3000/products/1



### 특정상품삭제하기
DELETE  http://localhost:3000/products/2
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM



### 특정상품옵션수정및추가하기
PATCH  http://localhost:3000/products/3/edit/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{
    "size_price":
        [{
            "size":"100g",
            "price":100000
        },{
            "size":"250g",
            "price":200000
        },{
            "size":"500g",
            "price":300000
        }],
    "taste_name":["Banan"],
    "grinding_name":[""]    
}   



### 특정상품옵셥삭제하기
PATCH  http://localhost:3000/products/3/edit/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{   
    "size_price":
        [{
            "size":"100g",
            "price":100000
        }],
    "taste_name":["Peach"],
    "grinding_name":["모카포트"]    
}


/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////장바구니 API///////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////

###
// 장바구니 전체리스트
GET http://localhost:3000/carts/ldy
Authorization: eyJhbGciOiJIUzI1NiJ9.bGR5.52hpg9uRII0cFL3crlnx6y_u_5V-T08G_B3rdNR3QyY



###
// 장바구니 생성하기
POST http://localhost:3000/carts/ldy/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.bGR5.52hpg9uRII0cFL3crlnx6y_u_5V-T08G_B3rdNR3QyY

{
    "items":[
        {
            "quantity":"1",
            "size":"100g",
            "grinding":"드립"
        },
        {
            "quantity":"1",
            "size":"250g",
            "grinding":"드립"
        }
    ]
}



###
// 장바구니 옵션 수정하기
PATCH  http://localhost:3000/carts/kdy?productId=3&size=100g&quantity=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.bGR5.52hpg9uRII0cFL3crlnx6y_u_5V-T08G_B3rdNR3QyY



###
// 장바구니 삭제하기
DELETE  http://localhost:3000/carts/kdy?productId=7&productId=9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.bGR5.52hpg9uRII0cFL3crlnx6y_u_5V-T08G_B3rdNR3QyY
