/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////유저 API//////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////
// 회원가입
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name":"kim do yeon",
    "username":"kdy",
    "email":"kdy@gamil.com",
    "password":"password1",
    "address":"korea",
    "phone_number":"010-0000-0000"
}


###
// 로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username":"kdy",
    "password":"password1"
}

/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////상품 API//////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////

###
// 상품등록하기
POST http://localhost:3000/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{
    "category_name" : "커피",
    "subcategory_name": "드립백",
    "size_price":
        [{
            "size":"100g",
            "price":10000
        },{
            "size":"250g",
            "price":25000
        },{
            "size":"500g",
            "price":50000
        }],

    "taste_name":["Grape"],
    "grinding_name":["모카포트"],
    "product_name" : "첫번째 커피",
    "roastingDate" : "2023-02-01"
}



###
// 전체상품리스트
GET http://localhost:3000/products

###
// 카테고리별리스트
GET http://localhost:3000/products/커피


###
// 특정상품정보
GET http://localhost:3000/products/커피/2



### 특정상품삭제하기
DELETE  http://localhost:3000/products/커피/4
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM



### 특정상품옵션수정및추가하기
PATCH  http://localhost:3000/products/커피/5/edit/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{
    "size_price":
        [{
            "size":"100g",
            "price":3333
        },{
            "size":"250g",
            "price":4444
        },{
            "size":"500g",
            "price":5555
        }],
    "taste_name":["Grape"],
    "grinding_name":["모카포트"]    
}   



### 특정상품옵셥삭제하기
PATCH  http://localhost:3000/products/커피/5/edit/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{   
    "size_price":
        [{
            "size":"250g",
            "price":222
        }],
    "taste_name":["Grape"],
    "grinding_name":["모카포트"]    
}


/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////장바구니 API///////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////

###
// 장바구니 전체리스트
GET http://localhost:3000/carts/kdy
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM



###
// 장바구니 생성하기
POST http://localhost:3000/carts/kdy/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{
    "items":[
        {
            "quantity":"1",
            "size":"100g",
            "grinding":"갈지않음"
        },
        {
            "quantity":"1",
            "size":"250g",
            "grinding":"모카포트"
        }
    ]
}



###
// 장바구니 옵션 수정하기
PATCH  http://localhost:3000/carts/kdy/5?&size=250g&quantity=5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM




###
// 장바구니 삭제하기
DELETE  http://localhost:3000/carts/kdy/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM


/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////주문 API//////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////
###
// 유저의 주문 전체리스트
GET   http://localhost:3000/orders
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

###
// 유저의 주문 상세리스트
GET   http://localhost:3000/orders/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

###
// 유저의 주문생성하기
POST   http://localhost:3000/orders
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.a2R5.95a4t68WOn8CjQTk9yyaJPHXqwUzWRN1dXYEQgjiahM

{
    "orderItems":[{
        "product_id": 1,
        "size": "250g",
        "grinding":"드립",
        "quantity":10
    },
    {
        "product_id": 2,
        "size": "500g",
        "grinding":"에스프레소",
        "quantity":5
    }]
}
